pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub')
    }

    stages{
        stage('Clone Repo'){
            steps {
                checkout scm // clones the code from source control
                sh 'ls *'
            }
        }
        stage('Build Image') {
            steps{
                sh 'docker build -t alexmeng99/jenkinsdockerpract:$BUILD_NUMBER ./alexproj/' // this is where the dockerfile is
            }
        }
        stage('Docker Login') {
            steps {
                //sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW' (this will leave the password visible)
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'                
                }
            }
        // stage('Run Tests') {
        //     steps{
        //         sh 'docker run --rm alexmeng99/jenkinsdockerpract:$BUILD_NUMBER'
        //     }
        // }
        stage('Run Tests') {
            steps {
		        //sh 'docker push raj80dockerid/jenkinstest' (this will use the tag latest)    
                sh 'docker run --rm alexmeng99/jenkinsdockerpract:$BUILD_NUMBER -c "go test"'
            }
        }
        stage('Docker Push') {
            steps {
		        //sh 'docker push raj80dockerid/jenkinstest' (this will use the tag latest)    
                sh 'docker push alexmeng99/jenkinsdockerpract:$BUILD_NUMBER'
            }
        }
    }
    post {
		always {
			sh 'docker logout'
		}
	}
}